### 1. Import the numpy package under the name `np` (★☆☆)
импортируйте библиотеку numpy, переименовав ее на **np**

In [ ]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)
Выведите на печать версию numpy и ее конфигурацию

In [ ]:
print(np.__version__ )

np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

### 3. Create a null vector of size 10 (★☆☆)
Создайте нулевой вектор размера 10

In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
Как найти размер памяти занимаемый вектором

In [ ]:
z = np.zeros((10))

print(z.itemsize*z.size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)  
Как получить документацию по функции numpy add (сложение) из командной строки?

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
Как создать вектор размера 10, пятый элемент которого = 1

In [ ]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
Создайте вектор со значениями от 10 до 49

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
Инвертировать вектор (первый элемент становится последним)

In [ ]:
z = np.arange(10,50)

np.flip(z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
Создайте матрицу 3x3 со значениями от 0 до 8


In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from array \[1,2,0,0,4,0\] (★☆☆)
Найдите индексы ненулевых элементов из вектора \[1,2,0,0,4,0\]

In [ ]:
a = np.array( [1,2,0,0,4,0])

print(np.where(a!=0))

print(np.nonzero(a))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
Создайте единичную матрицу 3x3

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)
Создайте массив 3 на 3 на 3 со случайными значениями

In [ ]:
np.random.randint(low=0, high=100, size=(3,3,3)).shape

(3, 3, 3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения

In [ ]:
a = np.random.randint(low=0, high=100, size=(10, 10))

print(a.min(), a.max())

5 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
Создайте случайный вектор размером 30 и найдите среднее значение

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Создайте двумерный-массив с 1(единицами) на границе и 0(нулями) внутри

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Как добавить границу (заполненную нулями) вокруг существующего массива (например: массив 5 на 5 из единиц окружить нулями, чтобы он превратился в массив 7 на 7?

#### 17. What is the result of the following expression? (★☆☆)
Каков результат следующих выражений ?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
3 * 0.1

0.30000000000000004

In [ ]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Создайте матрицу 5 на 5 со значениями 1,2,3,4 сразу ниже диагонали

In [ ]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Создайте матрицу 8x8 и залейте ее шахматным узором
Пояснение к заданию: не используйте функцию tile. Ниже будет аналогичное задание 21 с использованием функции tile

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
Рассмотрим массив формы (6,7,8), каков индекс (x, y, z) 100-го элемента?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Создайте матрицу шахматной доски 8x8, используя функцию tile

#### 22. Normalize a 5x5 random matrix (★☆☆)
Нормализовать матрицу случайных значений 5 на 5  

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Создайте настраиваемый dtype, который описывает цвет как четыре байта без знака (RGBA)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Умножьте матрицу 5x3 на матрицу 3x2 (матричное произведение)

In [ ]:
a = np.random.randint(7, size=(2,2))
b = np.random.randint(7, size=(2,2))


print(a)
print()
print(b)
print()

print(a @ b)


print(b @ a)


[[6 2]
 [5 1]]

[[0 3]
 [4 0]]

[[ 8 18]
 [ 4 15]]
[[15  3]
 [24  8]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
задан одномерный массив, инвертируйте (поменяйте знак) у всех элементов массива, которые находятся в диапазоне от 3 до 8, прямо в нем самом (без перезаписывания значений).

#### 26. What is the output of the following script? (★☆☆)
что выведет следующий скрипт?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
Каковы результаты следующих выражений?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)
Как округлить Вверх массив с плавающей запятой?  
(Необходимо реализовать не классическое математическое округление, а округление вверх по абсолютному значению (round(0)=0, round(0.1)=1, round(1)=1, round(-0.1)=-1 и round(-1)=-1) - то есть любое значение больше нуля это единица.)

#### 30. How to find common values between two arrays? (★☆☆)
Как найти общие значения между двумя массивами

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
Как игнорировать все предупреждения о numpy (не рекомендуется)

#### 32. Is the following expression true? (★☆☆)
Верно ли следующее выражение?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
Как получить даты вчера, сегодня и завтра

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
Как получить все даты, соответствующие июлю месяцу 2016

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Как вычислить ((A + B) * (- A / 2)) на месте (без копирования - то есть без создания дополнительного массива кроме существующих A, B)?

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
Извлеките целую часть случайного массива положительных чисел, используя 4 разных метода.

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
Создайте матрицу 5x5 со значениями строк от 0 до 4

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
Рассмотрим функцию генератора, которая генерирует 10 целых чисел и использует ее для построения массива.

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Создайте вектор размера 10 со значениями от 0 до 1, за исключением границ отрезка 0 и 1.

#### 40. Create a random vector of size 10 and sort it (★★☆)
Создайте случайный вектор размером 10 и отсортируйте его

#### 41. How to sum a small array faster than np.sum? (★★☆)
Как суммировать небольшой массив быстрее, чем np.sum

#### 42. Consider two random array A and B, check if they are equal (★★☆)
Рассмотрим два случайных массива A и B, проверьте, равны ли они

#### 43. Make an array immutable (read-only) (★★☆)
Сделать массив неизменным (только для чтения)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Рассмотрим случайную матрицу 10x2, представляющую декартовы координаты, преобразуйте их в полярные координаты.

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Создайте случайный вектор размером 10 и замените максимальное значение на 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
Создайте структурированный массив с координатами x и y, покрывающими область [0,1] x [0,1].

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
Для двух массивов, X и Y, построить матрицу Коши C (Cij = 1 / (xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
Выведите минимальное и максимальное представимое значение для каждого скалярного типа numpy

#### 49. How to print all the values of an array? (★★☆)
Как распечатать все значения массива?

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Как найти ближайшее значение (к заданному скаляру (числу)) в векторе?

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Создайте структурированный массив, представляющий позицию (x, y) и цвет (r, g, b)

#### 52. Consider a random vector with shape (5,2) representing coordinates, find point by point distances (★★☆)
Рассмотрим случайный вектор с формой (5,2), представляющей координаты, найдите расстояния от точки до точки (результат представьте в виде матрицы - таким образом должна получиться матрица 5 на пять где элемент с индексом i и j будет растоянием между точкой i и j)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? (★★★)
Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) на месте (без копирования)?  
В условии под термином без копирования подразумевается - без использования методов copy() или deepcopy(). В numpy существуют понятия копирования и представления массивов, но для новичков на которых расчитан данный материал это наверно сложновато. Ниже ссылка где разжевываются эти понятия.  

#### 54. How to read the following file? (★★☆)
Как прочитать следующий файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Что эквивалентно методу enumerate для массивов numpy?

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
Сгенерируйте универсальную 2D (двумерную) матрицу Гаусса  
Тут речь о двумерном универсальном нормальном (Гауссовом) распределении. Универсально означает, что медиана (μ) = 0, а дисперсия (σ) = 1.  

### 57. How to randomly place p elements in a 2D array? (★★☆)
Как случайным образом разместить p элементов в 2D-массиве?

### 58. Subtract the mean of each row of a matrix (★★☆)
Вычтите среднее значение каждой строки матрицы.  
Пояснение к заданию: необходимо вычислить среднее значение каждой строки матрицы и вычесть его из элементов соответствующей строки  

### 59. How to sort an array by the nth column? (★★☆)
Как отсортировать массив по n-му столбцу?

### 60. How to tell if a given 2D array has null columns? (★★☆)
Как определить, есть ли в данном 2D-массиве нулевые столбцы?

### 61. Find the nearest value from a given value in an array (★★☆)
Найдите ближайшее значение из заданного значения в массиве  
Это задание дублирует задание 50, но в том примере выше был одномерный массив. Давайте выполним задание для двумерного массива, чтобы изучить новый метод  

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
Имеются два массива с размерностями (1,3) и (3,1), как вычислить их сумму с помощью итератора?

#### 63. Create an array class that has a name attribute (★★☆)
Создайте массив-класс, с атрибутом name

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)  

Нам задан вектор, как добавить 1 к каждому элементу, индексируемому вторым вектором (будьте осторожны с повторяющимися индексами)?  

Пояснение к заданию: Например: есть два вектора Z = [0, 1] и I = [0, 0]. Второй вектор I воспринимается нами как индексы элементов  
первого вектора Z, то есть первый элемент I[0] вектора I, это индекс вектра Z => Z[I[0]]. Нам необходимо пройти по всем индексам i  
 вектора I и добавить 1(единицу) к каждому элементу Z[I[i]]. Таким образом понятно что значения вектора I не выходят за рамки len(X)  
 Самый простой способ проверки нашего алгоритма это проверка истинности выражения np.sum(Z_) == np.sum(Z) + len(I),  
 где Z_ преобразованный массив Z (то есть к которому добавили единицы).

#### 65. How to accumulate elements of a vector (Z) to an array (Sum_Z_I) based on an index list (I)? (★★★)

Как аккумулировать (просуммировать) элементы вектора (Z) в массив (Sum_Z_I) на основе индексного списка (I)?  
Пояснения к задаче: предположим, что у вас есть какой-нибудь вектор Z в котором указано время ответа сервера на запрос в секундах за последние N запросов. При этом в другом векторе I записанны номера соответствующих серверов к которым были адресованны эти запросы. Вам нужно создать вектор sum_Z_I в котором каждому номеру сервера из вектора I соответствовало суммарное время ответа на запросы из вектора Z (то есть сумма всех минут ответа соответвующего сервера). При этом, чтобы в полученном векторе sum_Z_I были рассчитаны все имеющиеся сервера с номерами от 0 до np.max(I). То есть если сервера под номером 2 нет в списке I, то в полученном векторе соответствующий элемент sum_Z_I[2] = np.nan.

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
Рассматривая (w, h, 3) изображение (dtype=ubyte), вычислите количество уникальных цветов.

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
Как получить суммы по двум последним осям заданного четырехмерного массива ?

#### 68. Considering a one-dimensional vector Z, how to compute means of subsets of D using a vector I of same size describing subset  indices? (★★★)

Как вычислить средние значения подмножеств заданного одномерного массива Z, используя вектор I того же размера, описывающий индексы подмножеств?  
Пояснения к задаче: предположим, что у вас есть какой-нибудь вектор Z в котором указано время ответа сервера на запрос в секундах за последние N запросов. При этом в другом векторе I записанны номера (индексы) соответствующих серверов к которым были адресованны эти запросы. Вам нужно создать вектор mean_Z_I в котором каждому номеру сервера из вектора I соответствовало бы среднее время ответа по запросам из вектора Z (то есть сумма всех минут ответа сервера поделенное на кол-во запросов к этому серверу). При этом, чтобы в полученном векторе mean_Z_I были рассчитаны все имеющиеся сервера с номерами от 0 до np.max(I). То есть если сервера под номером 2 нет в списке I, то в полученном векторе соответствующий элемент mean_Z_I[2] = np.nan.

#### 69. How to get the diagonal of a dot product? (★★★)
Как получить диагональ Скалярного произведение (векторов)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)  

Как умножить имеющийся массив размерности (5,5,3) на массив с размерами (5,5)  

#### 72. How to swap two rows of an array? (★★★)

Как поменять местами две строки массива?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
Рассмотрим набор из 10 триплетов, описывающих 10 треугольников (с общими вершинами), найдите набор уникальных (непересекающихся) отрезков, проходящих через все вершины треугольников.  
***Коммент к заданию*** я не очень догнал практический смысл этого обхода всех вершин треугольников один раз, может быть кто-нибудь знает где это полезно => напишите. Потому что во всех решениях которые я встречал применяется сортировка, которая меняет первоначальные триплеты.

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
Имея отсортированный массив C, который соответствует функции np.bincount, как создать массив A таким образом, чтобы np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array? (★★★)
Как рассчитать средние значения скользящего окна по массиву?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)  
Рассмотрим одномерный массив Z, построим двумерный массив, первая строка которого равна (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
Как реализовать отрицание логического значения или изменить знак числа с плавающей точкой в массиве без копирования (или без дополнительных переменных)?
В этом задании два вопроса давайте разберем и реализуем их отдельно:
1. Как реализовать отрицание логического значения? То есть требуется в массиве который задан значениями True(1) или False(0) реализовать трансформацию True(1)=>False(0) и наоборот False(0)=>True(1). И нужно реализовать это так, чтобы не создавать новых переменных и не занимать лишнюю память
2. Как реализовать изменение знака у вещественных элементов массива, чтобы не создавать новых переменных и не занимать лишнюю память?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
Рассмотрим 2 набора точек P0, P1, описывающих линии (2d) и точку p, как вычислить расстояние от p до каждой линии i (P0 [i],P1[i])?


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

Рассмотрим 2 набора точек P0, P1, описывающих линии (2d), и набор точек P, как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
Рассмотрим произвольный массив, напишите функцию, которая извлекает подраздел с фиксированной формой и центрирует его по заданному элементу (при необходимости дополните значением "fill").  
Эта задача очень распространенная в CV(компьютерном зрении), когда необходимо двигаться по картинке с окном заданного размера и применять к элементам окна разные агрегатные функции.  

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?  
Задача моделирует создание массива с окнами заданной ширины от исходного массива. Далее к этому массиву с окнами можно применять разные агрегирующие функции.  

#### 82. Compute a matrix rank (★★★)
Вычислите ранг матрицы

#### 83. How to find the most frequent value in an array?
Как найти наиболее часто встречающееся значение в массиве

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Извлеките все смежные блоки размером 3x3 из случайной матрицы размером 10x10  
Дополнение к заданию: Конкретно в этой задаче под смежные (contiguous) блоки подразумевается результат движения окна заданного размера с шагом 1. Но вообще говоря в англоязычных статьях смежные (contiguous) блоки матрицы или памяти подразумеваются рядом стоящие(имеющие общую границу) непересекающиеся блоки. Хотя в некоторых задачах на leetcode встречалась и такая пересекающаяся формулировка, но только она дополнялась примерами.  
Если представить что исходная матрица - квадратная размером (N, N), а размер окна size_window = s_w. Тогда кол-во смежных блоков = (N-s_w)*(N-s_w)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
Создайте подкласс 2D-массива таким образом, чтобы Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
Рассмотрим набор p матриц, имеющих форму (n, n), и набор p векторов с формой (n,1). Как вычислить сумму произведений матрицы p сразу? (результат имеет форму (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Рассмотрим массив 16x16, как получить сумму блоков (размер блока 4x4)  
Дополнение к заданию: В данном случае подразумевается стандартное блочное (клеточное) разбиение матрицы - блоки при разбиении не пересекаются. Кроме этого в условии задачи разбиение происходит на полные блоки 4 на 4 так как размер исходной матрицы 16 на 16. Но в случае, если размер блока не будет делить размер матрицы без остатка подразумевается что блочное разбиение в этом случае будет оставлять блоки меньше заданного размера слева и снизу.

***[np.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)*** - Возвращает новый массив, заполненный единицами.  

***[np.tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)*** - Строит массив, повторив массив A количество раз, заданное повторениями reps, по каждой оси.  

***[np.ufunc.reduceat](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html)*** - Выполняет (локальное) применение функции по указанным срезам по заданной оси.  

***[np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)*** - Возвращает равномерно распределенные значения в пределах заданного полуоткрытого интервала [start. stop). Для целочисленных аргументов функция эквивалентна встроенной функции range Python , но возвращает ndarray, а не список.  
Если вместо start и stop указывается только одно число, то по умолчанию start равен нулю, а stop равно заданному числу.  

#### 88. How to implement the Game of Life using numpy arrays? (★★★)
Как реализовать Игру жизни с использованием массивов numpy?  
[ссылка на описание игры на английском](https://en.wikipedia.org/wiki/Conway's_Game_of_Life) (к сожалению на [русском](https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%C2%AB%D0%96%D0%B8%D0%B7%D0%BD%D1%8C%C2%BB) описание скудное и не содержит описания основных узоров (паттернов) игры)  
Уточнение к заданию: стандартные условия Игры Жизни = B3/S23 (Birth if count neighbours equals 3 / Survive if count neighbours equals 2 or 3)

***[np.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)*** - возвращает новый массив заполненный нулями.  

#### 89. How to get the n largest values of an array (★★★)
Как получить n наибольших значений массива?  
Уточнение к заданию: В этой задаче целесообразно сделать акцент на очень больших массивах и обратить внимание на скорость выбранных методов  
Также целесообразно уточнить многомерный или одномерный массив. Ниже последовательно реализованы оба решения  

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
Учитывая произвольное количество векторов, постройте декартово произведение (все комбинации каждого элемента)

#### 91. How to create a record array from a regular array? (★★★)
Как создать массив записей из обычного массива?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
Рассмотрим большой вектор Z, вычислите Z в степени 3, используя 3 различных метода

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, которые содержат элементы каждой строки B независимо от порядка элементов в B?
Пояснение к заданию:
```python
например массив B = [[4 3]
                     [1 2]]
тогда в строка [0, 2, 4] в матрице A искомая, потому что содержит один элемент [2] из одной строки и элемент [4] из другой строки массива B.  Получается строка содержит элементы из всех (двух) строк массива B.
А например, строка [0, 1, 2] не подходит, потому что содежит элемент [2] только из одной строки [1, 2] массива B. Тогда как из другой строки [4, 3] массива B элементов в ней нет.  
```


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Рассматривая матрицу 10x3, извлеките строки с неравными значениями (например, [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
Преобразуйте вектор целых чисел в матричное двоичное представление
Уточнение для задания: допустим на входе массив = (0, 1, 8) тогда двоичное представление чисел
```python
0 (десятичное число) = 0b0 (двоичное представление)
1 (десятичное число) = 0b1 (двоичное представление)
8 (десятичное число) = 0b1000 (двоичное представление)
```
$$8 = 1*2^3 + 0*2^2 + 0*2^1 + 0*2^0$$  
так как для записи числа 0b1000 необходимо 4 (четыре) столбца, то на выходе будем иметь матрицу  
```python
[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 0]]
```
где первая строка соответвует числу 0, вторая строка числу 1 и последняя строка числу 8.

подразумевается, что числа положительные, иначе придется выделять отдельный столбец

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
Учитывая двумерный массив, как извлечь уникальные строки?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
Рассматривая 2 вектора A и B, запишите эквивалент einsum функции inner, outer, sum и mul

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
Рассматривая путь, описываемый двумя векторами (X, Y), как сделать выборку с использованием равноудаленных выборок

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
Учитывая целое число n и 2D-массив X, выберите из X строки, которые могут быть интерпретированы как взятые из мультиномиального распределения с n степенями, т.Е. строки, которые содержат только целые числа и сумма которых равна n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
Вычислите загрузочные 95% доверительные интервалы для среднего значения 1D массива X (т.Е. выполните повторную выборку элементов массива с заменой N раз, вычислите среднее значение каждой выборки, а затем вычислите процентили по средним значениям). (★★★)