<p><b>Подключение библиотек и функций</b></p>

In [ ]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
def getSE(sigma, n):
    return sigma / np.sqrt(n)

def getSE2(sigma1, n1, sigma2, n2):
    return np.sqrt(sigma1**2 / n1 + sigma2**2 / n2)

def getZ(x, mu, se):
    return (x - mu) / se

def getPrByX(x, mu, se):
    return stats.norm.cdf(x, loc=mu, scale=se)

def getPrByZ(z):
    return stats.norm.cdf(z, loc=0, scale=1)

def getZbyPr2Tail(pr):
    return stats.norm.ppf((1-pr)/2, loc=0, scale=1)

def getZbyPr1Tail(pr):
    return stats.norm.ppf(1-pr, loc=0, scale=1)

def getPValue1Tail_Norm(z):
    return 1 - stats.norm.cdf(z, loc=0, scale=1)

def getPValue2Tail_Norm(z):
    return 2 * (stats.norm.cdf(-abs(z), loc=0, scale=1))

def getPValue2Tail_T(t, df):
    return 2 * stats.t.cdf(-abs(t), df=df)

def getPValue1Tail_T(t, df):
    return 1 - stats.t.cdf(t, df=df)

<p>Создание генеральных совокупностей</p>

In [ ]:
mu1 = 70
sigma1 = 30
population1 = stats.norm.rvs(size=10000, loc=mu1, scale=sigma1)

In [ ]:
mu2 = 60
sigma2 = 20
population2 = stats.norm.rvs(size=10000, loc=mu2, scale=sigma2)

In [ ]:
mu3 = 2
sigma3 = 2
diff = stats.norm.rvs(size=10000, loc=mu3, scale=sigma3)
population3 = list(zip(population1, population1 + diff))

<p><b><i>Выборка</i></b></p>

<p>Исходные данные</p>

In [ ]:
n = 40
sample_2015 = np.random.choice(population1, n, replace=False)
sample_2015

array([ 95.29904931,  45.46900501,  60.17249447,  47.87139067,
        78.99709407,  62.29424128, 101.79810407,  48.82980493,
        73.56760369,  68.39744223,  83.25524325,  58.4188242 ,
        75.96483102,  95.41877565,  71.42702359,  92.21497588,
        90.7795942 ,  83.81000845,  35.63529845,  35.76685896,
        26.76562886,  34.16660519,  80.71738182,  56.83141815,
        34.75026294,  23.20201803,  33.88617144,  91.22762851,
        70.91317527, 106.3417718 ,  16.5919933 ,  55.82647414,
        81.01787608,  48.93922848,  66.7448425 ,  27.5483402 ,
        79.17951078,  42.33019988,  56.72656991,  93.61153366])

<p>Статистики выборки</p>

In [ ]:
#Среднее значение
x_bar = None # Your code here
print(x_bar)

#Выборочная дисперсия
var_2015 = None # Your code here
print(var_2015)

#Стандартное отклонение (несмещенное)
s_2015 = None # Your code here
print(s_2015)

63.31765735727136
591.9051323005966
24.329100523870515


<p><b><i>Доверительный интервал</i></b></p>

In [ ]:
#Уровни доверия: 95%, 90%, 80%
prs = np.array([0.95, 0.9, 0.8])

In [ ]:
#Стандартная ошибка
se = None # Your code here
se

3.846768553931327

In [ ]:
#Доверительный интервал
lowers, uppers = None # Your code her)
for i in range(len(prs)):
    print("Уровень доверия %i%%: (%f, %f)" % (prs[i]*100, lowers[i], uppers[i]))

Уровень доверия 95%: (55.778130, 70.857185)
Уровень доверия 90%: (56.990286, 69.645029)
Уровень доверия 80%: (58.387825, 68.247490)


In [ ]:
#Доверительный интервал для t-распределения (при небольших n)
lowers_t, uppers_t = None # Your code here
print("t-распределение")
for i in range(len(prs)):
    print("Уровень доверия %i%%: (%f, %f)" % (prs[i]*100, lowers_t[i], uppers_t[i]))

t-распределение
Уровень доверия 95%: (55.536834, 71.098481)
Уровень доверия 90%: (56.836333, 69.798982)
Уровень доверия 80%: (58.302861, 68.332453)


<p>или</p>

In [ ]:
#z-значения для двустороннего интервала
zs = None # Your code here
zs

array([-1.95996398, -1.64485363, -1.28155157])

In [ ]:
#z-значения для двустороннего интервала
zs = None # Your code here
zs

array([-1.95996398, -1.64485363, -1.28155157])

In [ ]:
#Предельная ошибка
delta = None # Your code here
delta

array([7.53952782, 6.32737121, 4.92983226])

In [ ]:
#Доверительный интервал
lowers = None # Your code here
uppers = None # Your code here

for i in range(len(prs)):
    print("Уровень доверия %i%%: (%f, %f)" % (prs[i]*100, lowers[i], uppers[i]))

Уровень доверия 95%: (55.778130, 70.857185)
Уровень доверия 90%: (56.990286, 69.645029)
Уровень доверия 80%: (58.387825, 68.247490)


<p>$$H_0: \mu_{2014}=\mu_{2015}$$<p>
<p>$$H_A: \mu_{2014} \neq \mu_{2015}$$<p>

<p><b><i>Выборка</i></b></p>

<p>Исходные данные</p>

In [ ]:
mu_2014 = 65
n = 40
alpha = 0.05 #уровень значимости
sample_2015 = np.random.choice(population1, n, replace=False)
sample_2015

array([ 40.53603612,  12.2003088 , 101.33882055,  50.9917911 ,
        35.12776537,  68.68433507,  66.8029707 ,  66.6260119 ,
        71.02398181,  61.23602316,  78.03804575,  63.24253296,
        74.66730301,  65.2043461 ,  18.57846332,  77.2098614 ,
        52.50323636,  23.64261497, 111.19657857,  49.39318842,
        57.10516408,  96.68127617,  89.38271441,  59.82283977,
        73.70829694,  76.30809903, 109.82426872,  41.27730762,
        37.82785751,  49.64264471,  82.09347212, 102.63773142,
        74.96657792,  69.25905148,  71.51553511,  51.6425729 ,
       121.66721325, 129.00108852, 101.6450525 ,  82.03719191])

In [ ]:
#Среднее значение
x_bar_2015 = None # Your code here
print(x_bar)

#Стандартное отклонение (несмещенное)
s_2015 = None # Your code here
print(s_2015)

#Стандартная ошибка
se = None # Your code here
print(se)

63.31765735727136
26.99178259083528
4.2677755547560094


<p><b>Проверка гипотезы</b></p>

In [ ]:
#Z-score
z = None # Your code here
z

0.9741033083219183

In [ ]:
#P-Value
pvalue = None # Your code here
pvalue

0.3300052470457966

In [ ]:
#P-Value для t-распределения
df = n - 1 #степень свободы
pvalue_t = None # Your code here
pvalue_t

0.3360087261184035

<p>или</p>

In [ ]:
tvalue, pvalue_t = None # Your code here
pvalue_t

0.3360087261184035

In [ ]:
pvalue_t = None # Your code here
pvalue_t

0.3360087261184035

<p><b>Проверка гипотезы на соответствие уровню значимости $\alpha$</b></p>

In [ ]:
if alpha > pvalue:
    print("alpha > p-value")
    print("Отказываемся от нулевую гипотезы в пользу альтернативной")
else:
    print("alpha <= p-value")
    print("Принимаем нулевую гипотезу (не отказываемся от нулевой гипотезы)")

alpha <= p-value
Принимаем нулевую гипотезу (не отказываемся от нулевой гипотезы)


<p><b><i>Выборка</i></b></p>

<p>Исходные данные</p>

In [ ]:
alpha = 0.05 #уровень значимости

In [ ]:
import random

n_items = 40
sample_items = np.array(random.sample(population3, n_items))
sample_items

array([[ 95.16631603,  94.6637336 ],
       [ 57.50511817,  62.47924395],
       [ 21.96480311,  22.09152879],
       [ 69.78452818,  67.97622281],
       [128.38679866, 128.99974334],
       [111.2092408 , 109.65072275],
       [ 38.83983958,  38.7147873 ],
       [ 72.51918723,  74.73406968],
       [ 45.24644237,  44.27319179],
       [134.99499884, 134.30930991],
       [ 71.34629748,  74.06765821],
       [104.29999127, 107.23714641],
       [107.78718896, 109.96129117],
       [118.2022069 , 121.17432763],
       [ 50.99008285,  49.49095703],
       [ 81.79288107,  82.70016837],
       [110.58221655, 113.73226353],
       [ 14.68259886,  16.76408253],
       [ 56.53216125,  60.45392798],
       [ 49.17498201,  54.0186    ],
       [ 62.43816157,  63.45239583],
       [ 77.41677267,  78.49193492],
       [ 33.25255462,  37.63482512],
       [ 63.40802792,  66.32130644],
       [ 39.45482131,  41.18096511],
       [ 58.21479958,  58.83319454],
       [ 74.97708923,  75.97400762],
 

In [ ]:
sample_diff = sample_items[:,0] - sample_items[:,1]
sample_diff

array([ 0.50258244, -4.97412578, -0.12672568,  1.80830537, -0.61294468,
        1.55851806,  0.12505228, -2.21488245,  0.97325059,  0.68568893,
       -2.72136074, -2.93715514, -2.17410221, -2.97212072,  1.49912582,
       -0.9072873 , -3.15004699, -2.08148368, -3.92176674, -4.843618  ,
       -1.01423426, -1.07516225, -4.38227051, -2.91327851, -1.7261438 ,
       -0.61839496, -0.99691839, -0.15911619, -0.5429068 ,  0.72881507,
       -0.15781045, -0.01104019, -2.57388588, -0.3825998 , -0.59951127,
       -2.87476339, -1.74823088, -5.37642708, -1.16017581, -5.68535479])

In [ ]:
#Среднее значение
x_bar_diff = None # Your code here
print("x_bar_diff =", x_bar_diff)

#Стандартное отклонение (несмещенное)
s_diff = None # Your code here
print("s_diff =", s_diff)

#Стандартная ошибка
se_diff = None # Your code here
print("se_diff =", se_diff)

x_bar_diff = -1.4938626691754087
s_diff = 1.9615101567255893
se_diff = 0.31014198744033533


<p><b>Проверка гипотезы</b></p>

<p>$$H_0: \mu_{diff}=0$$<p>
<p>$$H_A: \mu_{diff} \neq 0$$<p>

In [ ]:
#Z-score
z = None # Your code here
z

-4.816705669247044

In [ ]:
#P-Value
pvalue = None # Your code here
pvalue

1.4594772386822552e-06

In [ ]:
#P-Value для t-распределения
df = None # Your code here

pvalue_t = None # Your code here
pvalue_t

2.2294309097664822e-05

<p>или</p>

In [ ]:
tvalue, pvalue_t = None # Your code here
print("t-value =", tvalue)
print("p-value =", pvalue_t)

t-value = -4.816705669247044
p-value = 2.2294309097664822e-05


In [ ]:
pvalue_t = 2 * stats.t.cdf(-abs(tvalue), df)
pvalue_t

2.2294309097664822e-05

<p><b>Проверка гипотезы на соответствие уровню значимости $\alpha$</b></p>

In [ ]:
if alpha > pvalue:
    print("alpha > p-value")
    print("Отказываемся от нулевую гипотезы в пользу альтернативной")
else:
    print("alpha <= p-value")
    print("Принимаем нулевую гипотезу (не отказываемся от нулевой гипотезы)")

alpha > p-value
Отказываемся от нулевую гипотезы в пользу альтернативной


<p><b><i>Выборка</i></b></p>

<p>Исходные данные</p>

In [ ]:
alpha = 0.05 #уровень значимости

In [ ]:
n_london = 40
sample_london = np.random.choice(population1, n_london, replace=False)
sample_london

array([ 90.75078532,  94.48790637,  20.90906195,  59.05337362,
        82.06665674,  58.24777067,  93.79031646,  38.78633186,
        10.72151927,  82.91078687,  41.82336595,  57.49888434,
        32.26435865,  58.03656886,  23.14778819,  17.23748644,
        56.98624403,  50.33610974, 121.5336427 ,  55.89762868,
       101.15055255,  84.89585884,  85.762544  ,  74.26687583,
        50.44344485,  38.75446041,  37.59553856, 113.2408705 ,
        72.60633959,  92.65610239, 108.28831128,  36.78813824,
        97.99089277,  61.40120274,  39.87212379,  72.20258634,
        59.03084842,  96.39796808,  93.61153366,  34.22559982])

In [ ]:
n_moscow = 50
sample_moscow = np.random.choice(population2, n_moscow, replace=False)
sample_moscow

array([56.74526143, 85.08487202, 23.35801843, 81.9134661 , 70.20498389,
       55.81244397, 55.07654542, 80.71644656, 56.58292132, 48.29758003,
       61.65198624, 87.64884571, 55.7879653 , 57.83664488, 84.54481557,
       51.70624082, 64.87250756, 48.80729477,  3.55646911, 30.35123899,
       35.01809928, 76.57088931, 40.82304216, 42.47458107, -5.41029876,
       96.93832035, 56.46671658, 72.64501889, 38.59703624, 42.80138033,
       60.18491554, 40.7893726 , 46.29004857, 61.04349339, 46.83817378,
       61.90982267, 78.51464322, 55.0429175 , 53.63116899, 23.25971459,
       82.96309196, 62.95267538, 55.2352214 , 63.35865114, 41.98199782,
       54.41419113, 36.91342708, 86.81945064, -5.67872904, 74.20834375])

In [ ]:
#Среднее значение
x_bar_london = None # Your code here
x_bar_moscow = None # Your code here
print("x_bar_london =", x_bar_london)
print("x_bar_moscow =", x_bar_moscow)

#Стандартное отклонение (несмещенное)
s_london = None # Your code here
s_moscow = None # Your code here
print("s_london =", s_london)
print("s_moscow =", s_moscow)

#Стандартная ошибка
se_london_moscow = None # Your code here
print("se_london_moscow =", se_london_moscow)

x_bar_london = 64.94170948371121
x_bar_moscow = 54.76307851439969
s_london = 28.73358891182093
s_moscow = 22.50586749004621
se_london_moscow = 5.547139778609184


<p><b>Проверка гипотезы</b></p>

<p>$$H_0: \mu_{treated}-\mu_{control}=0$$<p>
<p>$$H_A: \mu_{treated}-\mu_{control} \neq 0$$<p>

In [ ]:
#Z-score
z = None # Your code here
z

1.834933204416849

In [ ]:
#P-Value
pvalue = None # Your code here
pvalue

0.06651558707750224

In [ ]:
#P-Value для t-распределения
df = None # Your code here
if n_london > n_moscow:
    df = n_moscow - 1

pvalue_t = None # Your code here
pvalue_t

0.0741513008689744

<p>или</p>

In [ ]:
tvalue, pvalue_t = None # Your code here
pvalue_t

0.07060460987663093

<p>или</p>

In [ ]:
tvalue, pvalue_t = None # Your code here
pvalue_t

0.07060460987663095

In [ ]:
pvalue_t = None # Your code here
pvalue_t

0.0741513008689744

<p><b>Проверка гипотезы на соответствие уровню значимости $\alpha$</b></p>

In [ ]:
if alpha > pvalue:
    print("alpha > p-value")
    print("Отказываемся от нулевую гипотезы в пользу альтернативной")
else:
    print("alpha <= p-value")
    print("Принимаем нулевую гипотезу (не отказываемся от нулевой гипотезы)")

alpha <= p-value
Принимаем нулевую гипотезу (не отказываемся от нулевой гипотезы)
